# Generated by Django 6.1.1 on 2026-09-21 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '00000000000000'. Up to 15 digits allowed", regex='^[\\d+]{4,15}$')]),
        ),
    ]
